export const GET_USER_CART_REQUEST= "GET_USER_CART_REQUEST";
export const GET_USER_CART_SUCCESS= "GET_USER_CART_SUCCESS";
export const GET_USER_CART_FAILURE= "GET_USER_CART_FAILURE";

export const ADD_CART_ITEM_REQUEST= "ADD_CART_ITEM_REQUEST";
export const ADD_CART_ITEM_SUCCESS= "ADD_CART_ITEM_SUCCESS";
export const ADD_CART_ITEM_FAILURE= "ADD_CART_ITEM_FAILURE";

export const DELETE_CART_ITEM_REQUEST= "DELETE_CART_ITEM_REQUEST";
export const DELETE_CART_ITEM_SUCCESS= "DELETE_CART_ITEM_SUCCESS";
export const DELETE_CART_ITEM_FAILURE= "DELETE_CART_ITEM_FAILURE";

export const UPDATE_CART_ITEM_REQUEST= "UPDATE_CART_ITEM_REQUEST";
export const UPDATE_CART_ITEM_SUCCESS= "UPDATE_CART_ITEM_SUCCESS";
export const UPDATE_CART_ITEM_FAILURE= "UPDATE_CART_ITEM_FAILURE";